newsport/accounts_test/urls.py
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'auth'
urlpatterns = [
    path('test_protect_page/', IndexViewProtect.as_view(), name='test_protect_page'),
    path('test_page/', cache_page(60)(IndexView.as_view()), name='test_page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('signup/', UserRegisterView.as_view(), name='signup'),
    # path('user/', UserView.as_view(), name='user_page'),
    path('upgrade/', upgrade_me, name ='upgrade'),
]

newsport/newsport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('pages.urls')),
    path('auth/', include('accounts_test.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include('appointment.urls')),
]

newsport/pages/urls.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'pages'
urlpatterns = [
    path('', cache_page(30)(PostView.as_view()), name='posts_view'),
    path('<int:pk>/', cache_page(60)(PostDetail.as_view()), name='post_detail'),
    path('', PostsSort.as_view()),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('user/', UserView.as_view(), name='user_page'),
    path('add/', CreatePostView.as_view(), name='create_post'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update_post'),
    path('<int:pk>/delete', PostDelete.as_view(), name='del_post'),
    path('сategory/', CategoryList.as_view(), name='categories'),
    path('сategory/<int:pk>', PostCategoryView.as_view(), name='category_detail'),
    path('<int:pk>/subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

newsport/pages/templates/pages/add_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Add news
{% endblock title %}

{% block content %}
<h1>Добавить</h1>

{% include 'parts/paginator.html' %}

<!--<form method="POST">-->
<!--   {% csrf_token %}-->
<!--   <label for="title" class="form-label">Заголовок</label>-->
<!--   <input name="title" id="title" class="form-control" type="text">-->
<!--   <label for="text" class="form-label">Текст статьи</label>-->
<!--   <input name="text" class="form-control text-post" id="text" type="text">-->

<!--   <label for="select" class="form-label">Type</label>-->
<!--   <select name="type" id="select" class="form-select">-->
<!--       <option selected>Open this select menu</option>-->
<!--       {% for type in choices %}-->
<!--       <option value="{{ type.0 }}">-->
<!--           {{ type.1 }}-->
<!--       </option>-->
<!--       {% endfor %}-->
<!--   </select>-->
<!--   <input class="btn btn-success" type="submit" value="Add">-->
<!--</form>-->

<form method="POST">
   {% csrf_token %}
   {{ form }}
   <br>
   <input class="btn btn-info" type="submit" value="Save">
   <br>
</form>

{% endblock content %}

newsport/pages/templates/pages/category_detail.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %} Category {% endblock title %}

{% block content %}
<h1>Категория {{ category }}</h1>
<br>
<hr>
<br>
{{ subscribers }}
{% if is_not_subscribed %}
    <a class="btn btn-info" href="{% url 'pages:subscribe' category.pk %}">Подписаться</a>
{% else %}
    <p>Вы подписаны на данную категорию.</p>
    <a class="btn btn-info" href="{% url 'pages:unsubscribe' category.pk %}">Отписаться</a>
{% endif %}
<br>
<br>

{% if post %}
    <table class="table table-striped table-hover">
        <tr>
            <th scope="col">Дата</th>
            <th scope="col">Автор</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Текст</th>
        </tr>
        {% for p in post %}
            <tr>
                <td>{{ p.date }}</td>

                <td>{{ p.author }}</td>

                <td><a href="{% url 'pages:posts_view' %}{{ p.id }}">{{ p.title }}</a></td>

                <td>{{ p.text }}</td>
            </tr>
        {% endfor %}
        </table>

        {% include 'parts/paginator.html' %}

    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

{% endblock content %}

newsport/pages/templates/pages/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Категории
{% endblock title %}

{% block content %}
  {% if categories %}
        <h1>Категории новостей</h1>
        <table class="table table-striped table-hover">
            <thead>
                <th scope="col">Категория</th>
            </thead>
            {% for c in categories %}
            <tr>
                <td><a href="{% url 'pages:categories' %}{{ c.id }}">{{ c.name }}</a></td>
            </tr>
            {% endfor %}
        </table>

        {% include 'parts/paginator.html' %}

    {% else %}
        <h2>Категорий нет!</h2>
    {% endif %}
{% endblock content %}

newsport/pages/templates/pages/del_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Delete Post
{% endblock title %}

{% block content %}

<h3>Delete this product?</h3>
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.title }}
   </h3>
   <div>
     Автор: <span class="badge bg-info">{{ post.author }}</span>
   </div>
 </div>
    <div class="card-body">
   {{ post.text|truncatechars:20 }}
 </div>
</div>

<br>

<form method="POST">
 {% csrf_token %}
   <input class="btn btn-info" type="submit" value="Delete">
</form>



{% endblock content %}

newsport/pages/templates/pages/mail_new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новая статья</title>
</head>
<body>
    <h2>Приветствуем, <strong>{{user.username}}</strong></h2>
    <h3>
        В рубрике <strong>{{category.name}}</strong> появился новый пост от <strong>{{post.author}}</strong>
    </h3>
    <p>Нажмите на ссылку ниже, чтобы прочитать статью:
        <a href="http://127.0.0.1:8000{% url 'pages:post_detail' post.id %}"> <h3>{{ post.title }}</h3> </a>
        {{ post.text|truncatechars:30 }}
    </p>


</body>
</html>

newsport/pages/templates/pages/mail_subscribed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подписка</title>
</head>
<body>
    <h2>Подписка на сайте "NewsPort"</h2>
    <p>
        <strong>{{ user.username }}</strong>, Вы успешно подписаны на категорию: "{{ category.name }}"!
    </p>

</body>
</html>

newsport/pages/templates/pages/mail_weekly_posts.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Еженедельный список новых статей</title>
</head>
<body>
        <h2>Приветствуем, {{ sub.username }}!</h2>
        <p>Ниже представлен список новых статей по категории {{ cat.name }} за последнюю неделю:</p>
        <ul>
            {% for post in post_list %}
                <li><a href="http://127.0.0.1:8000/{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
</body>
</html>

newsport/pages/templates/pages/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Все статьи</h1>
<p>Количество статей: {{ news|length }}</p>
<hr> <br>
<a href="add" class="add-news"><button class="btn btn-info">Написать пост</button></a>
{% if news %}
<!--    <form method="GET">-->
<!--   {{ filter.form }}-->
<!--   <input class="btn btn-primary me-2 btn-outline-light" type="submit" value="Найти">-->
<!--    </form>-->
    <br> <br>
    <a href="search" class="search-btn">Расширенный поиск</a>
    <br> <br>
    <table class="table table-striped table-hover">
        <tr>
            <th scope="col">
                Дата
            </th>
            <th scope="col">
                Автор
            </th>
            <th scope="col">
                Заголовок
            </th>
            <th scope="col">
                Текст
            </th>
            <th scope="col">
                Категории
            </th>
            <th scope="col">
                Рейтинг
            </th>
            <th scope="col">
                Действия
            </th>
        </tr>
        {% for post in news %}
        <tr>
            <td>
<!--                {{ post.date }}-->
                {{ post.date|date:'d m y' }}
            </td>
            <td>
                {{ post.author }}
            </td>
            <td>
                <a href="{{ post.id }}" class="open-post">{{ post.title|censor }}</a>
            </td>
            <td>
<!--                {{ post.preview }}-->
<!--                {{ post.text|truncatewords:20 }}-->
                {{ post.text|truncatechars:20|censor }}
            </td>
            <td>
                {% for c in post.category.all %}
                    <a href="{% url 'pages:categories' %}{{ c.pk }}">{{ c.name }}</a> |
                {% endfor %}
            </td>
            <td>
                {{ post.rating }}
            </td>

            <th>
                <a href="{% url 'pages:update_post' post.id  %}">
                    Ред.
                </a> ||
                <a href="{% url 'pages:del_post' post.id %}">
                    Удалить
                </a>
            </th>
        </tr>
        {% endfor %}
    </table>

{% else %}
    <h3>Статей нет</h3>
{% endif %}

{% include 'parts/paginator.html' %}

<!--<form method="POST">-->
<!--   {% csrf_token %}-->
<!--   <label for="title" class="form-label">Заголовок</label>-->
<!--   <input name="title" id="title" class="form-control" type="text">-->
<!--   <label for="text" class="form-label">Текст статьи</label>-->
<!--   <input name="text" class="form-control text-post" id="text" type="text">-->

<!--   <label for="select" class="form-label">Type</label>-->
<!--   <select name="type" id="select" class="form-select">-->
<!--       <option selected>Open this select menu</option>-->
<!--       {% for type in choices %}-->
<!--       <option value="{{ type.0 }}">-->
<!--           {{ type.1 }}-->
<!--       </option>-->
<!--       {% endfor %}-->
<!--   </select>-->
<!--   <input class="btn btn-success" type="submit" value="Add">-->
<!--</form>-->

<!--<form method="POST">-->
<!--   {% csrf_token %}-->
<!--   {{ form }}-->
<!--   <input class="btn btn-success" type="submit" value="Add">-->
<!--</form>-->
<br> <br>
{% endblock content %}

newsport/pages/templates/pages/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}

{% if post %}
<div class="card">
    <div class="card-header">
        <h3>{{ post.title|censor }}</h3>
        <div>
            Автор: <span class="badge bg-info">{{ post.author }}</span>
        </div>
        <div>
            <span>{{ post.date|date:'d m y, H:i' }}</span>
        </div>
        <div>
            Категории:
            {% for c in post.category.all %}
                <a href="{% url 'pages:categories'%}{{ c.pk }}">{{ c.name }}</a> |
            {% endfor %}
        </div>
    </div>
    <div class="card-body">
        <span>{{ post.text|censor }}</span>
    </div>
    <div>
        <span class="card-body"><a href="{% url 'pages:update_post' post.id %}">Редактировать</a> </span>
        <span class="card-body"><a href="{% url 'pages:del_post' post.id %}">Удалить</a> </span>
        <br>
        <br>
    </div>

</div>

{% else %}
    <h3>Страница не существует</h3>
{% endif %}

<br><br>

{% endblock content %}

newsport/pages/templates/pages/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Search
{% endblock title %}
{% block content %}
<h1>Search</h1>
<h3>(Всего новостей: {{ news|length }})</h3>
<form method='GET'>
    {{ filter.form }}
    <input class="btn btn-primary" type='submit' value='Найти'>
</form>
<table class="table">
    <tr>
        <th scope="col">
            Заголовок
        </th>
        <th scope="col">
            Дата публикации
        </th>
        <th scope="col">
            Текст
        </th>
        <th scope="col">
                Категории
        </th>
    </tr>
    {% for post in filter.qs %}
        <tr>
            <td>
                <a href="{{ post.get_absolute_url }}">{{ post.title|censor }}</a>
            </td>
            <td>
                {{ post.date|date:'d.m.Y' }}
            </td>
            <td>
                {{ post.text|truncatechars:50|censor }}
            </td>
            <td>
                {% for c in post.category.all %}
                    <a href="{% url 'pages:categories'%}{{ c.pk }}">{{ c.name }}</a>
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
{% endblock content %}

newsport/pages/templates/pages/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<br>
<h1 class="text-center">{{ message }} "{{ category }}"</h1>
<br>
{% endblock content %}

newsport/pages/templates/pages/unsubscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<br>
<h1 class="text-center">{{ message }} "{{ category }}"</h1>
<br>
{% endblock content %}

newsport/pages/templates/pages/user_page.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
Профиль
{% endblock title %}

{% block content %}
<br>
<h2>Страница авторизованного пользователя "{{request.user.username}}"</h2>
<br>
<div>
    <h6> Информация </h6>
</div>
<br>

{% if is_not_author %}
    <a href="{% url 'auth:upgrade' %}"><button type="button" class="btn btn-info">Стать автором</button></a>
{% else %}
    <span>Приветствуем, автор!</span>
    <br> <br>
    <a href="{% url 'pages:create_post' %}" class="add-news"><button class="btn btn-info">Написать пост</button></a>
{% endif %}
<br><br>
{% if subscribers %}
    {% for category in subscribers %}
        <a href="{% url 'pages:categories'%}((category.pk))"> {{ category.name }}</a> || <a href="{% url 'pages:unsubscribe' category.pk %}">Отписаться</a> <br>
    {% endfor %}
{% endif %}
<br><br>
<a href="{% url 'account_logout' %}"><button class="btn btn-info"> Выйти </button></a>
<!--<button class="btn btn-info"> <a href="{% url 'auth:logout' %}">Выйти</a> </button>-->
<br><br>
{% endblock content %}