newsport/accounts_test/urls.py
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'auth'
urlpatterns = [
    path('test_protect_page/', IndexViewProtect.as_view(), name='test_protect_page'),
    path('test_page/', cache_page(60)(IndexView.as_view()), name='test_page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('signup/', UserRegisterView.as_view(), name='signup'),
    # path('user/', UserView.as_view(), name='user_page'),
    path('upgrade/', upgrade_me, name ='upgrade'),
]

newsport/newsport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('pages.urls')),
    path('auth/', include('accounts_test.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include('appointment.urls')),
]

newsport/pages/urls.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'pages'
urlpatterns = [
    path('', cache_page(30)(PostView.as_view()), name='posts_view'),
    path('<int:pk>/', cache_page(60)(PostDetail.as_view()), name='post_detail'),
    path('', PostsSort.as_view()),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('user/', UserView.as_view(), name='user_page'),
    path('add/', CreatePostView.as_view(), name='create_post'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update_post'),
    path('<int:pk>/delete', PostDelete.as_view(), name='del_post'),
    path('сategory/', CategoryList.as_view(), name='categories'),
    path('сategory/<int:pk>', PostCategoryView.as_view(), name='category_detail'),
    path('<int:pk>/subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

newsport/accounts_test/models.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from django.contrib.auth.models import User
# from allauth.account.forms import SignupForm
# from django.contrib.auth.models import Group
#
#
# # Форма регистрации
# class UserRegistrationForm(UserCreationForm):
#     email = forms.EmailField(label="Email")
#     password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
#     password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm Password')
#
#     class Meta:
#         model = User
#         fields = ("username",
#                   "email",
#                   "password1",
#                   "password2",)
#
#         widgets = {
#             'username': forms.TextInput(attrs={'class': 'form-control'}),
#             'email': forms.EmailInput(attrs={'class': 'form-control'})
#         }
#
#     def clean(self):
#         username = self.cleaned_data.get('username')
#         email = self.cleaned_data.get('email')
#         if User.objects.filter(username=username).exists():
#             raise forms.ValidationError("Пользователь с таким именем уже существует")
#         if User.objects.filter(email=email).exists():
#             raise forms.ValidationError("Пользователь с таким email уже существует")
#         return super().clean()
#
#
# # Форма входа
# class UserLoginForm(AuthenticationForm):
#     class Meta:
#         model = User
#         fields = (
#             "username",
#             "password",
#         )

newsport/accounts_test/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User, Group
from allauth.account.forms import SignupForm


# Форма регистрации
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='Password')
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='Confirm Password')

    class Meta:
        model = User
        fields = ("username",
                  "email",
                  "password1",
                  "password2",)

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Пользователь с таким именем уже существует")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return super().clean()


# Форма входа
class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "password",
        )


# Форма входа для переопределения allauth
class BasicSignupForm(SignupForm):
    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get_or_create(name='users')[0]
        basic_group.user_set.add(user)
        return user

newsport/accounts_test/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render
from django.views.generic import TemplateView
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from .models import *
from .forms import *


# Тестовые страницы, чтобы проверять работоспособность
class IndexViewProtect(LoginRequiredMixin, TemplateView):
    template_name = 'pages/test_protect_page.html'


class IndexView(TemplateView):
    template_name = 'pages/test_page.html'


class UserView(TemplateView):
    template_name = 'pages/user_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        context['subscribers'] = category.subscribers.filter()
        return context


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'pages/register.html'
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        # group = Group.objects.get(name='my_group')
        group = Group.objects.get_or_create(name='users')[0]

        user.groups.add(group)  # добавляем нового пользователя в эту группу
        user.save()
        return super().form_valid(form)


class UserLoginView(FormView):
    model = User
    form_class = UserLoginForm
    template_name = 'pages/login.html'
    success_url = '/'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserLogoutView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


@login_required
def upgrade_me(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/')

newsport/accounts_test/templates/pages/login.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
Login
{% endblock title %}

{% block content %}

<h1>Login</h1>
<br><br>
<p>Вы не в системе</p>
<br><br>
<form method="post" action="{% url 'auth:login' %}" class="py-3">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <br><br>
    <button type="submit" class="btn btn-info">
        <span>Вход</span>
    </button>
</form>

<br><br>

<a class="btn btn-info" href="{% url 'auth:signup' %}"> Регистрация </a>

<br><br>

{% endblock content %}

newsport/accounts_test/templates/pages/logout.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
Logout
{% endblock title %}

{% block content %}
<h1>Logout</h1>
<br><br>
<h2> Вы вышли из системы </h2>
<br><br>
{% endblock content %}

newsport/accounts_test/templates/pages/register.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
Registration
{% endblock title %}

{% block content %}
<h1>Registration</h1>
<br><br>
<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-info" value="Send">
</form>
<br><br>
{% endblock content %}

newsport/accounts_test/templates/pages/test_page.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
test page
{% endblock title %}

{% block content %}
<h1>test page</h1>
{% endblock content %}

newsport/accounts_test/templates/pages/test_protect_page.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
test protect page
{% endblock title %}

{% block content %}
<h1>test protect page</h1>
 <h2>
   Страница авторизованного пользователя {{request.user.username}}
 </h2>

 <div>
   Здесь может содержаться персональная информация для каждого пользователя
 </div>
<a class="btn btn-primary" href="logout/">Выйти</a>

{% endblock content %}

newsport/accounts_test/templates/pages/user_page.html
{% extends 'flatpages/default.html' %}
<!--{% load custom_filters %}-->

{% block title %}
Профиль
{% endblock title %}

{% block content %}
<br>
<h2>Страница авторизованного пользователя "{{request.user.username}}"</h2>
<br>
<div>
    <h6> Информация </h6>
</div>
<br>

{% if is_not_author %}
    <a href="{% url 'auth:upgrade' %}"><button type="button" class="btn btn-info">Стать автором</button></a>
{% else %}
    <span>Приветствуем, автор!</span>
    <br> <br>
    <a href="{% url 'pages:create_post' %}" class="add-news"><button class="btn btn-info">Написать пост</button></a>
{% endif %}
<br><br>
<a href="{% url 'account_logout' %}"><button class="btn btn-info"> Выйти </button></a>
<!--<button class="btn btn-info"> <a href="{% url 'auth:logout' %}">Выйти</a> </button>-->
<br><br>
{% endblock content %}